# Generated by Django 4.0.4 on 2022-07-15 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='artist', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='genre', to='genres.genres')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
